Added CMS markdown support.
fingerprintjs/fingerprintjs.com pull request #101
Opened 2021-01-20 20:28 UTC by tan-90

Card content, image block text and CTA subtitle for the static page can now be edited as markdown.

2021-01-22 11:53 UTC, Lisenish requested changes

2021-01-22 11:53 UTC, Lisenish commented on content/index/account-sharing.md
> +      markdownContent: Account sharers already know the value of your service. By enforcing
Maybe we should change it to more visible prefix and more robust to accidental name conflict `markdown__`?
I think probably no need to change everything again now, just an idea, maybe for the future?

2021-01-22 11:53 UTC, Lisenish commented on src/components/widgets/CardGrid/CardGrid.module.scss
> +    p,
Why this is copied in each client component? I assume we need small correction in each place, probably can't avoid it to get the best results? 

Maybe we should at least extract it to scss mixin with some arguments for customization, so you don't have to copy it over in each place

2021-01-22 11:53 UTC, Lisenish commented on src/components/Post/Post.tsx
> +    // We might not have all the data while editing the post on  the CMS, but we still want the preview to display what we have.
Minor: several levels of `if` nesting is usually a code smell. We can leave the check in the begging of function just add there `&& !editing` and just on if below with editing, it would be easier to read

2021-01-22 11:53 UTC, Lisenish commented on src/templates/static-page-content.tsx
> +    importRemark()
Parsing markdown content and replacing it

This is similar task, see how https://github.com/react-syntax-highlighter/react-syntax-highlighter approach syntax highlighting, I think it's similar.

We don't need HOC component for this, probably it's a stretch since we need this only for CMS preview pages, so let's do all the parsing work in effect, and we may even extract it to custom hook after that, but it's up to you.

I think it's fine if we get a blink of raw markdown on first render, if it bother someone we could implement processing... state later

2021-01-22 12:14 UTC, Lisenish commented on src/templates/static-page-content.tsx
> +    importRemark()
Another approach: we probably also could use React.Lazy since it's browser-only page, so should work here. And even if we need dynamically imported components with SSR support I think there is a separate lib for it. But it's probably too much here, let's do what I wrote above

2021-01-22 12:44 UTC, tan-90 commented on src/components/widgets/CardGrid/CardGrid.module.scss
> +    p,
Yeah, the font sizes are always different from the blog post, which is the primary use of the Content component. I'll make a mixin.

2021-01-22 13:06 UTC, tan-90 commented on content/index/account-sharing.md
> +      markdownContent: Account sharers already know the value of your service. By enforcing
I agree. It's easy to change with a find and replace, so I did it already.

2021-01-22 18:11 UTC, tan-90 commented on src/templates/static-page-content.tsx
> +    importRemark()
Discussed on call. Changed to a cleaner, but still not ideal approach. Waiting on consistent typography so we can revisit this.

2021-01-28 21:08 UTC, Lisenish approved these changes

2021-01-29 12:05 UTC, merged