Fix sporadic incorrect logo sizes
fingerprintjs/fingerprintjs.com pull request #104
Opened 2021-01-27 12:23 UTC by natapg

Closes WEB-62

2021-01-27 12:35 UTC, tan-90 commented on src/components/Header/index.tsx
> +                  <LogoSvg alt='FingerprintJS' className={styles.logo} />
Very minor thing, is TS ok with the alt prop? For me it complains when I add `alt` to an imported SVG.

2021-01-27 12:55 UTC, natapg commented on src/components/Header/index.tsx
> +                  <LogoSvg alt='FingerprintJS' className={styles.logo} />
Yes, you are right. I think I should use a title element instead of an alt tag. Thanks

2021-01-27 13:13 UTC, natapg commented on src/components/Header/index.tsx
> +                  <LogoSvg alt='FingerprintJS' className={styles.logo} />
@tan-90 I added a title element to the SVG file based on this https://css-tricks.com/accessible-svgs/

2021-01-27 19:03 UTC, Lisenish requested changes

2021-01-27 19:03 UTC, Lisenish commented on src/img/fpjs.svg
> +<svg preserveAspectRatio="xMidYMid meet" x="0px" y="0px" viewBox="0 0 450 63" xmlns="http://www.w3.org/2000/svg" data-name="Layer 1" aria-labelledby="logoTitle"><title id="logoTitle">FingerprintJS</t
We store local images (the ones which is used only in one place) inside component subfolder, please move it to the `Header` folder

2021-01-27 19:26 UTC, natapg commented on src/img/fpjs.svg
> +<svg preserveAspectRatio="xMidYMid meet" x="0px" y="0px" viewBox="0 0 450 63" xmlns="http://www.w3.org/2000/svg" data-name="Layer 1" aria-labelledby="logoTitle"><title id="logoTitle">FingerprintJS</t
done @Lisenish

2021-01-28 20:43 UTC, Lisenish approved these changes

2021-01-28 20:44 UTC, merged