Added Paywall use case page
fingerprintjs/fingerprintjs.com pull request #107
Opened 2021-01-27 15:59 UTC by natapg

Closes WEB-106

2021-01-27 16:35 UTC, tan-90 approved these changes

2021-01-27 17:10 UTC, Lisenish commented on static/admin/config.yml
> +  branch: feature/use-case-paywall
Don't forget to change back before the merge

2021-01-27 17:11 UTC, Lisenish requested changes
LGTM 👍 
I've set "Request changes" so we don't merge it accidentally before changing backing branch back

2021-01-28 20:58 UTC, Lisenish commented
@natapg I saw that Savannah requested to change Custom Solution card, are you going to do it in this PR?

2021-01-28 21:03 UTC, natapg commented
> @natapg I saw that Savannah requested to change Custom Solution card, are you going to do it in this PR?

yea, I think it's a good idea to do it in this PR

2021-01-29 15:42 UTC, natapg commented
> @natapg I saw that Savannah requested to change Custom Solution card, are you going to do it in this PR?

done

2021-01-29 20:28 UTC, Lisenish requested changes

2021-01-29 20:28 UTC, Lisenish commented on src/components/UseCasesSection/index.tsx
> -            <UseCase onClick={() => setIsContactSalesModalOpen(true)} icon={CustomSolutionSvg} title='Custom Solution'>
Since you deteled custom solution we don't need "Contact Sales" modal here anymore and everything what it used (isContactSalesModalOpen state)

2021-01-29 20:38 UTC, natapg commented on src/components/UseCasesSection/index.tsx
> -            <UseCase onClick={() => setIsContactSalesModalOpen(true)} icon={CustomSolutionSvg} title='Custom Solution'>
you're right, I'm going to remove the unused code

2021-01-29 20:48 UTC, natapg commented on src/components/UseCasesSection/index.tsx
> -            <UseCase onClick={() => setIsContactSalesModalOpen(true)} icon={CustomSolutionSvg} title='Custom Solution'>
done @Lisenish

2021-02-18 18:48 UTC, natapg commented on static/admin/config.yml
> +  branch: feature/use-case-paywall
done @Lisenish

2021-02-18 18:49 UTC, natapg commented
> LGTM 👍
> I've set "Request changes" so we don't merge it accidentally before changing backing branch back

done @Lisenish

2021-02-18 19:30 UTC, Lisenish approved these changes
LGTM

2021-02-18 19:30 UTC, merged