Features/fix navigation bar
fingerprintjs/fingerprintjs.com pull request #116
Opened 2021-02-08 16:51 UTC by natapg

Closes WEB-105

2021-02-08 21:05 UTC, natapg commented
I have updated the PR using sticky position instead of fixed position, this way it is not necessary to add margin or padding to the content since the header is still part of the flow of the page @Lisenish

2021-02-10 13:28 UTC, tan-90 requested changes

2021-02-10 13:28 UTC, tan-90 commented on src/components/Header/Header.module.scss
> +    z-index: 9999;
`custom-properties.scss` has `z-index` variables, we should use those.

2021-02-10 13:28 UTC, tan-90 commented on src/components/Header/Header.module.scss
> +    background: white;
There's a variable for white as well, you can get the value with `c('white')`.

2021-02-11 12:07 UTC, tan-90 approved these changes

2021-02-11 15:29 UTC, merged