Added new AB video test
fingerprintjs/fingerprintjs.com pull request #123
Opened 2021-03-03 18:12 UTC by natapg

Closes WEB-112

2021-03-03 19:38 UTC, tan-90 requested changes

2021-03-03 19:38 UTC, tan-90 commented on src/components/YoutubeEmbed/YoutubeEmbed.tsx
> +        title='Embedded youtube'
The iframe should have a descriptive title passed as a prop.

2021-03-03 19:38 UTC, tan-90 commented on src/components/LiveDemoSection/index.tsx
> +          <h2 className={styles.title}>Installing FingerprintJS Pro</h2>
I don't love the word "Installing" in this situation. I'd go with something like "Getting started", but that's just a personal nitpick.

2021-03-04 14:48 UTC, natapg commented on src/components/LiveDemoSection/index.tsx
> +          <h2 className={styles.title}>Installing FingerprintJS Pro</h2>
I agree, I'm going to ask Savannah

2021-03-04 19:43 UTC, tan-90 approved these changes

2021-03-05 11:00 UTC, Lisenish requested changes
@natapg Mostly minor comments, good job Nata!

2021-03-05 15:32 UTC, natapg commented on src/components/YoutubeEmbed/YoutubeEmbed.module.scss
> +  padding-bottom: 56.25%;
a percentage value for padding-bottom and the position in relative keep the aspect ratio of the container ( ie 56.25% = 16:9 )

2021-03-05 15:38 UTC, natapg commented on src/components/YoutubeEmbed/YoutubeEmbed.module.scss
> +  position: absolute;
Is to take a fixed position relative to the parent <div> and keep the aspect ratio.
Changing it to relative or static looks like this
![image](https://user-images.githubusercontent.com/47128448/110137522-b5eeb180-7daf-11eb-8ea6-6f0b39fcfb79.png)

2021-03-05 15:40 UTC, natapg commented on src/components/LiveDemoSection/LiveDemoSection.module.scss
> +  > * + * {
Since it is not my code, it will take me a while to analyze it

2021-03-05 15:41 UTC, natapg commented
@Lisenish done 👍

2021-03-05 16:08 UTC, Lisenish approved these changes

2021-03-05 16:08 UTC, Lisenish commented on src/components/LiveDemoSection/index.tsx
> +import YoutubeEmbed from '../YoutubeVideo/YoutubeVideo'
Rename this too please

2021-03-05 17:26 UTC, Lisenish commented
Closing PR, since it will be our current AB test branch

2021-03-05 17:26 UTC, closed without merging