Feature: GitHub pro layers section
fingerprintjs/fingerprintjs.com pull request #129
Opened 2021-03-16 19:09 UTC by natapg

Second GitHub Landing page section

ticket : https://fpjs.myjetbrains.com/youtrack/issue/WEB-115

2021-03-16 19:45 UTC, tan-90 commented on src/components/githubPage/ProLayersSection/ProLayersSection.tsx
> +interface layerProps {
Typo here, should be LayerProps

2021-03-16 19:57 UTC, tan-90 approved these changes
Only one minor comment, approving in advance.

2021-03-24 15:39 UTC, Lisenish requested changes

2021-03-24 15:39 UTC, Lisenish commented on src/components/githubPage/ProLayersSection/ProLayersSection.module.scss
> +$ossColor: rgb(67, 72, 118);
Maybe we should move it to other color vars? Or you don't expect us reusing it somewhere else?

2021-03-24 15:39 UTC, Lisenish commented on src/components/githubPage/ProLayersSection/ProLayersSection.tsx
> +            <img alt='FingerprintJS Pro layers' src={proLayers} className={styles.image} />
We should always use `Img` from 'gatsby-image' for big images to automatically get all benefits from Gatsby optimisations

2021-03-24 15:39 UTC, Lisenish commented on src/components/githubPage/ProLayersSection/ProLayersSection.tsx
> +        <div className={styles.wrapper}>
A lot div's here, let's try to use semantic HTML (`aside`. `section`, `article` ,...)

2021-03-24 15:39 UTC, Lisenish commented on src/pages/github/index.tsx
> +    <LayoutTemplate siteMetadata={siteMetadata}>
You should've created this branch based on the other already created, so you don't need to recreate this page.

2021-03-24 21:11 UTC, natapg commented on src/components/githubPage/ProLayersSection/ProLayersSection.module.scss
> +$ossColor: rgb(67, 72, 118);
I didn't think about it, but maybe it can be used in the future, I'll move it with the other variables

2021-03-24 21:17 UTC, natapg commented on src/components/githubPage/ProLayersSection/ProLayersSection.module.scss
> +$ossColor: rgb(67, 72, 118);
or maybe I can adjust our brand-water color since it's the base color

2021-03-24 23:08 UTC, natapg commented on src/components/githubPage/ProLayersSection/ProLayersSection.tsx
> +            <img alt='FingerprintJS Pro layers' src={proLayers} className={styles.image} />
done, please check when you have a time

2021-03-24 23:25 UTC, natapg commented on src/components/githubPage/ProLayersSection/ProLayersSection.tsx
> +        <div className={styles.wrapper}>
done

2021-03-24 23:28 UTC, natapg commented on src/pages/github/index.tsx
> +    <LayoutTemplate siteMetadata={siteMetadata}>
yeah, I realized after creating the branch. For the next branches I will take it into account

2021-03-25 09:48 UTC, Lisenish approved these changes
Good job

2021-03-26 16:55 UTC, merged