[WIP] Add customizable CTA
fingerprintjs/fingerprintjs.com pull request #259
Opened 2021-08-17 23:07 UTC by natapg

Closes WEB-179 & WEB-155

2021-08-19 13:41 UTC, natapg commented on src/components/Content/Content.module.scss
> +    content: url('../../img/plus-simbol.svg');
changed to relative path to fix problem with storybook

2021-08-19 13:44 UTC, natapg commented on static/admin/config.yml
> +  branch: feat/WEB-179-add-customizable-CTA-blogs
I'll change it after Savannah updates CTAs and before merging

2021-08-19 18:51 UTC, tan-90 approved these changes
Looks good to me, really nice touch that on mobile you can scroll over the CTA and it will scroll the page below.

2021-08-19 20:11 UTC, Lisenish requested changes

2021-08-19 20:11 UTC, Lisenish commented on static/admin/config.yml
> +  branch: feat/WEB-179-add-customizable-CTA-blogs
Aren't they optional? Maybe she could update it directly on the prodcution?

2021-08-19 20:11 UTC, Lisenish commented on src/templates/long-form-content.tsx
> +          <div className={styles.header}>
We're using a lot of div's, let's try to use more semantic tags as well (probably no need to change anything here, but mostly for the future).
@tan-90 FYI for you as well

https://dev.to/kenbellows/stop-using-so-many-divs-an-intro-to-semantic-html-3i9i

2021-08-19 20:11 UTC, Lisenish commented on src/components/CustomizableCTA/CloseSVG.svg
> +<svg width="10" height="10" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg">
We still didn't have `cross` svg in the websire? Maybe we should make it common and not local then? I think we will probably reuse it if it doesn't look very custom

2021-08-19 20:11 UTC, Lisenish commented on src/templates/long-form-content.tsx
> +          {customCTA.subHeader && (
So we have two instances of CustomizableCTA component? 
I understand that it's for mobile probably but I belive there should be a way to implement it with styles only, since we're using Grid now can't we display everything as we needed with it?

2021-08-19 23:15 UTC, natapg commented on static/admin/config.yml
> +  branch: feat/WEB-179-add-customizable-CTA-blogs
they are optional, but we need at least one, because otherwise the graphql query fails, and the one that is set is an example

2021-08-19 23:16 UTC, natapg commented on src/components/CustomizableCTA/CustomizableCTA.tsx
> +  useEffect(() => {
ok 👍🏻

2021-08-19 23:19 UTC, natapg commented on src/components/CustomizableCTA/CloseSVG.svg
> +<svg width="10" height="10" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg">
we don't have another, only in the modal that we no longer use, and it is not the same, but yea, it's a good idea to move it to a shared folder

2021-08-20 01:44 UTC, natapg commented on src/components/CustomizableCTA/CustomizableCTA.tsx
> +  useEffect(() => {
done @Lisenish

2021-08-20 02:15 UTC, natapg commented on src/templates/long-form-content.tsx
> +          <div className={styles.header}>
done @Lisenish

2021-08-20 02:17 UTC, natapg commented on src/templates/long-form-content.tsx
> +          {customCTA.subHeader && (
done @Lisenish

2021-08-20 12:37 UTC, tan-90 commented on src/components/CustomizableCTA/CustomizableCTA.tsx
> +  })
Sorry about missing it. I probably would have made the same mistake 😓
I'll be more careful.

2021-08-23 07:53 UTC, Lisenish commented on static/admin/config.yml
> +  branch: feat/WEB-179-add-customizable-CTA-blogs
Oh yeah makes sense, so you may ask Savannah to add at least one and say that she will be able to add the rest at her own pace later, probably it will be faster for her

2021-08-23 08:11 UTC, Lisenish commented on src/hooks/useShowOnScroll.ts
> +export const useShowOnScroll = () => {
I actually meant something more generic, like this https://usehooks.com/useEventListener/ (but maybe only focused on scroll).
But it's fine also as long as we don't have any other use cases, we may need to refactor it later if we will need to attach some other logic to scrolling

2021-08-23 08:11 UTC, Lisenish commented on src/components/CustomizableCTA/CustomizableCTA.tsx
> +  })
@tan-90 It's fine, just wanted to make sure that we're doing attentive reviews

2021-08-23 08:12 UTC, Lisenish approved these changes

2021-08-23 15:37 UTC, merged