Holy new site
fingerprintjs/fingerprintjs.com pull request #34
Opened 2020-11-19 17:56 UTC by holy-devs

2020-11-19 17:58 UTC, holy-devs commented
Let me know if there are any questions regarding the code and whether you want me to jump on a call for a quick walkthrough?

2020-11-20 10:02 UTC, Lisenish requested changes
Only minor things
Could you please sync master and resolve conflicts?

2020-11-20 10:02 UTC, Lisenish commented on src/js/fpjs-widget.js
> +  ipResolution: 'full',
Only formatting changes here, right?

2020-11-20 10:02 UTC, Lisenish commented on webpack.config.js
> +        // console.log(data);
Leftover comment

2020-11-20 10:02 UTC, Lisenish commented on src/css/index.scss
> +// @import './container';
Leftover comment here and on top of the file

2020-11-20 10:41 UTC, holy-devs commented on src/js/fpjs-widget.js
> +  ipResolution: 'full',
Yeah that's probably my Prettier plugin...

2020-11-20 15:30 UTC, Lisenish commented on src/js/fpjs-widget.js
> +  ipResolution: 'full',
Ok, that's fine

2020-11-20 19:39 UTC, Lisenish approved these changes
LGTM

2020-11-20 19:41 UTC, merged