new fields : added sales and signup flows
fingerprintjs/fingerprintjs.com pull request #345
Opened 2021-10-26 01:07 UTC by natapg

2021-11-01 02:19 UTC, natapg commented on src/context/HistoryListener.tsx
> +  if (isNonEuUser) {
@Lisenish My idea here is to send the cookie data if it is a non-EU user, but if it is an EU user, we still send the available information to salesforce through the lead form and to the API through the embedded form.

2021-11-01 20:23 UTC, Lisenish requested changes

2021-11-01 20:23 UTC, Lisenish commented on src/context/HistoryListener.tsx
> +    }
Looks like useless `else` block, I think we can just remove it? Or you can move it to the top and check `if (!isEuUser) { return }` and put the big block outside of the if

2021-11-01 20:23 UTC, Lisenish commented on src/context/HistoryListener.tsx
> +      setCookie(utmParamsCookie, JSON.stringify(historyData.utmParams), 30)
Do we need 3 different cookies? Why not just store the full object here?

2021-11-01 20:23 UTC, Lisenish commented on src/context/HistoryListener.tsx
> +    return globalHistory.listen(({ action }) => {
```suggestion
    historyData.visitedPages.push(globalHistory.location.pathname)

    return globalHistory.listen(({ action }) => {
```

2021-11-01 20:23 UTC, Lisenish commented on src/context/HistoryListener.tsx
> +    const urlParamsEntries = new URLSearchParams(globalHistory.location.search).entries()
I'm not sure if it's correct that we're using `globalHistory` everywhere now and not `location` from the reach custom hook. Probably it's fine, it works?

2021-11-01 20:23 UTC, Lisenish commented on src/context/HistoryListener.tsx
> +      })
Do we need two listeners for it? You can set it in the previous listener, no? Or you didn't want to check for region there?

2021-11-01 20:23 UTC, Lisenish commented on src/context/HistoryListener.tsx
> +const utmParamsCookie = 'utmParams'
We should have only one cookie, also let's name it in some less obvious more and common way so it's not very suspicious for users, e.g. `fpjsWebsiteData`. We can later use it for something else as well

2021-11-01 20:23 UTC, Lisenish commented on src/context/HistoryListener.tsx
> +    const utmParams = getCookie(utmParamsCookie)
You're reading and parsing cookie multiple times here: 
1. It's expensive to do it on each render
2. It's a side effect and you shouldn't do that in render function. Take a look at this example https://medium.com/swlh/react-hooks-usecookie-hook-26ac06ff36b0. Or https://github.com/reactivestack/cookies/tree/master/packages/react-cookie (we don't need necessary add this as a dep, just an example)

2021-11-01 20:38 UTC, natapg commented on src/context/HistoryListener.tsx
> +  if (isEuUser === false) {
I tried that, but during rendering the value is undefined so the condition doesn't pass and it tries to get the cookies giving the following error
`error "document" is not available during server side rendering`

2021-11-01 20:53 UTC, natapg commented on src/context/HistoryListener.tsx
> +    const urlParamsEntries = new URLSearchParams(globalHistory.location.search).entries()
yeah, it works! tested several times using utm params

2021-11-01 20:55 UTC, natapg commented on src/context/HistoryListener.tsx
> +      })
I didn't want to check the region there and add it to the deps,I want to prevent the effect from running and add duplicates to the array

2021-11-02 02:42 UTC, natapg commented on src/context/HistoryListener.tsx
> +    const utmParams = getCookie(utmParamsCookie)
I've added a useEffect in this case, so it should just run once

2021-11-02 15:51 UTC, natapg commented on src/components/GetStartedForm/index.tsx
> -        lastPage: visitedPages[visitedPages.length - 1],
@Lisenish I'm going to add this value to the table from the API taking the last element of the visitedPages array in this way I don't have to send it here or from the dashboard

2021-11-02 20:25 UTC, Lisenish requested changes
@natapg Let's discuss src/context/HistoryListener.tsx on our call tomorrow

2021-11-02 20:25 UTC, Lisenish commented on src/context/HistoryListener.tsx
> +const fpjsWebsiteData = 'fpjsWebsiteData'
```suggestion
const trackingDataCookieName = 'fpjsWebsiteData'
```

2021-11-02 20:25 UTC, Lisenish commented on src/context/HistoryListener.tsx
> +    if (isEuUser === false) {
I already wrote about nesting, it's better to invert this condition, probably I wans't clear enough I will show to you on our call

2021-11-02 20:25 UTC, Lisenish commented on src/context/HistoryListener.tsx
>    useEffect(() => {
Please add comments for each effect, to clarify what they're responsible for

2021-11-02 20:25 UTC, Lisenish commented on src/context/HistoryListener.tsx
> +    setHistory(historyData)
We are always overwriting history with historyData here?

2021-11-02 20:25 UTC, Lisenish commented on src/context/HistoryListener.tsx
> +      const history: HistoryProps = historyDataCookies ? JSON.parse(historyDataCookies).historyData : historyData
I think we discussed that we doesn't need to read it from the cookies on the website side?

2021-11-03 16:01 UTC, Lisenish approved these changes

2021-11-03 16:01 UTC, Lisenish commented on src/context/HistoryListener.tsx
> +const trackingDataCookieName = 'fpjsWebsiteData'
There is an error above

2021-11-03 17:26 UTC, merged