fix: show validation error in contact sales form
fingerprintjs/fingerprintjs.com pull request #361
Opened 2021-11-08 15:56 UTC by natapg

Closes WEB-251

2021-11-15 16:50 UTC, tan-90 requested changes

2021-11-15 16:50 UTC, tan-90 commented on src/components/ContactSalesForm/index.tsx
> +        } else {
The `format` property is the name of the rule we used for validation. To get the name of the field we should use `instancePath`. It separates sub properties and array elements using `/`, but since on this form the only value with sub properties is the utm info, we can probably just remove the starting / and use what's left.

(For example if there's a validation error on the email, `instancePath` will be `/email`, but if it was an array of emails and the second email had an error, it would be `/email/1` or `/user/email` for objects)

https://ajv.js.org/api.html#error-objects

2021-11-15 16:52 UTC, tan-90 commented on src/components/ContactSalesForm/index.tsx
> +        } else {
We should also check if the error object will have a message, since that will usually be more descriptive:

```
error: {
              data: [
                {
                  instancePath: '',
                  keyword: 'required',
                  message: "must have required property 'emails'",
                  params: {
                    missingProperty: 'emails',
                  },
                  schemaPath: '#/required',
                },
              ],
              message: 'Validation error',
            },
```

2021-11-15 19:29 UTC, natapg commented on src/components/ContactSalesForm/index.tsx
> +        } else {
for example if I send an email like emai@localhost the error message is -> "must match format \"email\""
should I show this message insted of Validation error for email? what do you think?

2021-11-15 19:38 UTC, natapg commented on src/components/ContactSalesForm/index.tsx
> +        } else {
it could be something like this 
```
      if (error?.message) {
        if (error?.data[0]?.message) {
          updateErrorMessage(error?.data[0]?.message)
        } else if (error?.data[0]?.instancePath) {
          updateErrorMessage(`Validation error for ${error?.data[0]?.instancePath.substring(1)}`)
        } else {
          updateErrorMessage(error?.message)
        }
      }
```

2021-11-15 19:39 UTC, tan-90 commented on src/components/ContactSalesForm/index.tsx
> +        } else {
Good point, in this case the message from AJV is not that great. I think we can just change it to get the field name from the instance path and leave the message as is.

2021-11-16 11:59 UTC, tan-90 approved these changes

2021-11-16 12:44 UTC, merged