[Solutions Page] Solutions Overview Page
fingerprintjs/fingerprintjs.com pull request #367
Opened 2021-11-11 14:48 UTC by natapg

DP: https://deploy-preview-366--fingerprintjscom.netlify.app/solutions/
Mock-up: https://www.figma.com/file/niHrIRowTbqQhDO7W5CPNf/FPJS-WEB-UI-%2B?node-id=1976%3A13990
Ticket: https://fpjs.myjetbrains.com/youtrack/issue/WEB-255

*Using blogs for testing, the CMS integration will be rolled out in the next PR*

2021-11-11 16:47 UTC, borislobanov92 requested changes

2021-11-11 16:47 UTC, borislobanov92 commented on src/components/PostGrid/PostGrid.tsx
> +    }, timeout)
you can avoid some duplication in the last section:
```
const filteredSolutions = newSelectedTags.size === 0 ? posts : posts.filter((solution) => solution.tags?.some((tag) => newSelectedTags.has(tag)))

setNumberOfSolutions(filteredSolutions.length)
setTimeout(() => {
  setSelectedSolutions(filteredSolutions)
}, timeout)
```

2021-11-11 16:47 UTC, borislobanov92 commented on src/components/PostGrid/PostGrid.tsx
> +  const [selectedSolutions, setSelectedSolutions] = useState(posts)
this is a matter of taste but I think 'selected' is ok for tags because the user manually selects them but for solutions I'd use 'filtered' (as you did below in the  method). I believe it better reflects what that variable actually is

2021-11-11 16:47 UTC, borislobanov92 commented on src/components/PostGrid/PostGrid.tsx
> +  variant?: 'posts' | 'solutions'
I'd use enum for this instead of 'magic' strings.

2021-11-11 16:47 UTC, borislobanov92 commented on src/components/PostGrid/PostGrid.tsx
> +      )
this is too much code and it's hard to read, please refactor these into separate  local components (like Posts and SwiperPosts or smth), this  way the ternary will look much better

2021-11-11 16:47 UTC, borislobanov92 commented on src/components/PostGrid/PostGrid.tsx
> +          )}
actually, I don't see the reason to have the Solutions inside if of the PostGrid. It's great  that  you decided to  reuse thing but PostGrid is the building block and the Solutions is the business logic component. So ideally you should have two business components: Posts and Solutions and both of the inside should use a components named something like ContentGrid (a more generic name). otherwise we are putting logic into a presentational component, which is harder to maintain and reuse. with this approach if we  are working in a team and I need to build a grid based page I'll have to add another condition and rendering logic to this component, it will end up being a huge mess. what I'd want to  do instead is to take the Grid component, pass the data to  it  and  it will render the data  according to the settings.  let  me know if something is unclear, we  can get on a call and discuss.

2021-11-11 16:47 UTC, borislobanov92 commented on src/components/PostGrid/PostGrid.tsx
> +              </span>
please use <button> element for buttons instead of spans

2021-11-11 16:47 UTC, borislobanov92 commented on src/components/PostGrid/PostGrid.tsx
> +                {selectedTags.size > 0 && ` matching ${selectedTags.size} filter`}
'filter' is always singular, '18 solutions matching 3 filter' looks awkward. also, I think we should have some native  speaker proofread this line, I'm  not  sure if 3 tags are considered 3 filters, to me it's one filtering  systems, so maybe we should change the wording here

2021-11-11 16:47 UTC, borislobanov92 commented on src/components/solutions/HeroSection/HeroSection.tsx
> +        </section>
not sure if sections are correctly used here, usually the image and the description are one unit and you already have a section wrapper on top, so I'd probably just use divs here

2021-11-11 17:54 UTC, natapg commented on src/components/PostGrid/PostGrid.tsx
> +          )}
yeah, I agree, my idea is to move all the new logic into a new component SolutionGrid (because in this component we have the filter logic that we don't need in the post grid) but still reuse the Post component there because we have the same design

2021-11-11 17:57 UTC, natapg commented on src/components/PostGrid/PostGrid.tsx
> +                {selectedTags.size > 0 && ` matching ${selectedTags.size} filter`}
good point, I didn't notice the singular form there, I will talk to Kate and Sav about this

2021-11-15 15:49 UTC, borislobanov92 approved these changes

2021-11-15 15:49 UTC, borislobanov92 commented on src/components/Grid/Grid.tsx
> +  perRow?: 'four' | 'three'
I think it would be more logical if this was just a number type and limit it (but also have a default value)
```
type PerRow = 3 | 4
```

2021-11-15 15:49 UTC, borislobanov92 commented on src/components/Posts/Posts.tsx
> +  perRow?: 'four' | 'three'
I suggest that you create a separate type for it next to the Grid component and import it from there, so this interface looks  like
```
export type PostsProps = PerRow & {
  posts: Array<PostProps>
  name?: string
  link?: React.ReactNode
  tags?: string[]
  ...
}
```

2021-11-15 15:49 UTC, borislobanov92 commented on src/components/Posts/Posts.tsx
> +  limitPostLines?: boolean
there are several similarities between  this interface and SwiperPostsProps, please create a shared type and extend it in  both places

2021-11-15 15:49 UTC, borislobanov92 commented on src/components/solutions/Solution/Solution.tsx
> +    if (data.frontmatter) {
we already have this check at the  top of the method

2021-11-15 15:49 UTC, borislobanov92 commented on src/components/solutions/SolutionsSection/SolutionsSection.tsx
> +                ` matching ${selectedTags.size} ${selectedTags.size === 1 ? 'filter' : 'filters'}`}
Optional: it's better to make a helper for this,  like here this one https://github.com/fingerprintjs/dashboard/blob/2fa81f5ed34d4f50c449dc5459a976715b9421ad/src/helpers/pluralize.ts

2021-11-15 15:49 UTC, borislobanov92 commented on src/components/solutions/SolutionsSection/SolutionsSection.tsx
> +              className={classNames(styles.solutionsGrid, { [styles.fadeOut]: !fade }, { [styles.fadeIn]: fade })}
you can have  one object
```
{ 
  [styles.fadeOut]: !fade,
  [styles.fadeIn]: fade,
}
```

2021-11-15 18:54 UTC, merged