feat: added demo section to hero
fingerprintjs/fingerprintjs.com pull request #402
Opened 2021-12-02 16:11 UTC by natapg

Closes [WEB-279](https://fpjs.myjetbrains.com/youtrack/issue/WEB-279)

2021-12-02 17:58 UTC, natapg commented on src/hooks/useBotDResponse.ts
> +        // noop
not sure what to do in case of an error, just log the error message or use rollbar maybe?

2021-12-02 18:00 UTC, natapg commented on src/styles/vendors/tippy.scss
> -  z-index: 1;
removing this property because is interfering with the tippy arrow

2021-12-03 20:58 UTC, Lisenish reviewed
Approved but there're some comments

2021-12-03 20:58 UTC, Lisenish commented on src/hooks/useBotDResponse.ts
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
Let's leave a  TODO here to add types (I believe it's temporary until they didn't export types, correct?)

2021-12-03 20:58 UTC, Lisenish commented on src/hooks/useBotDResponse.ts
> +  const clientToken = BOTD_TOKEN
That's the purpose? You can just inline `BOTD_TOKEN`

2021-12-03 20:58 UTC, Lisenish commented on src/hooks/useBotDResponse.ts
> +        // noop
It's better to return it from the hook (see how react-query does it for example). You can return `isError` boolean property and error object.
What should we do depends on the errors, what are possible errors? Does BotD team have any guidelines regarding it, types for errors?

In this branch you can just return it, we can decided what to do/show on UI when you discussed the types of the errors with BotD team

2021-12-03 20:58 UTC, Lisenish commented on src/styles/vendors/tippy.scss
> -  z-index: 1;
Thanks for the comment. Are you sure it wouldn't break anything? (have you checked?) I wonder why it was here in the first place then

2021-12-03 20:58 UTC, Lisenish commented on src/components/botd/HeroSection/HeroSection.tsx
> +  const [detectedBots, setdetectedBots] = useState<DetectedBots>({
```suggestion
  const [detectedBots, setDetectedBots] = useState<DetectedBots>({
```

2021-12-03 20:58 UTC, Lisenish commented on src/components/botd/HeroSection/HeroSection.tsx
> +  const [isLoading, setIsLoading] = useState(true)
This `isLoading` property should be returned from you custom `useBotDResponse` hook

2021-12-03 20:58 UTC, Lisenish commented on src/hooks/useBotDResponse.ts
> +export const useBotDResponse = () => {
1. I think you can call it just `useBotD`.
2. We use function declaration everywhere, no?

2021-12-03 20:58 UTC, Lisenish commented on src/components/botd/HeroSection/HeroSection.tsx
> +        }))
You always need to update to dependant values in state together, probably you can replace these two states with one `useReducer`

2021-12-03 20:58 UTC, Lisenish commented on src/components/botd/HeroSection/HeroSection.tsx
> +  }
Looks like reusable helper, don't we have something similar already? 
Please extract to commons, may be helpful to use somewhere else

2021-12-03 20:58 UTC, Lisenish commented on src/components/botd/HeroSection/HeroSection.tsx
> +  const repeatElement = (length, fn) => Array.from({ length }, (_, i) => fn(i))
Also looks like a function which may be useful somewhere else as well, also it's not clear why do you need to recreate it on each render

2021-12-03 20:58 UTC, Lisenish commented on src/components/botd/HeroSection/HeroSection.tsx
> +    </div>
It would look better if you just do 
```
if (isLoading) {
  return <JSX>
}

return <JSX>
```

2021-12-03 20:58 UTC, Lisenish commented on src/components/botd/HeroSection/HeroSection.tsx
> +    <div className={styles.cards}>
Maybe `section`?

2021-12-03 20:58 UTC, Lisenish approved these changes

2021-12-03 20:59 UTC, Lisenish requested changes
Actually, I decided that I will take a 2nd look at the next version of the custom hook

2021-12-03 21:17 UTC, natapg commented on src/styles/vendors/tippy.scss
> -  z-index: 1;
I tried the tiptool in several browsers and it works fine, but I'm not sure why it was here this property, maybe I should find another way to solve the arrow problem without removing it

2021-12-03 21:18 UTC, natapg commented on src/hooks/useBotDResponse.ts
> +        // noop
thanks, I already sent a message to Rishat about this and he told me that he will talk with Valentin about this (and about who is going to create the docs in our docs page)

2021-12-08 20:20 UTC, Lisenish approved these changes
Good job @natapg

2021-12-08 20:20 UTC, Lisenish commented on src/styles/_mixins.scss
> +}
Please add comment with explanation why do we need it, also maybe we should extract 135px to the constants?

2021-12-08 21:29 UTC, merged