botd: API Response section
fingerprintjs/fingerprintjs.com pull request #404
Opened 2021-12-03 02:19 UTC by natapg

Closes [WEB-287](https://fpjs.myjetbrains.com/youtrack/issue/WEB-287)

2021-12-03 20:24 UTC, tan-90 requested changes
No major issues but I want to take a look at the changes so I'm leaving it red for now.

2021-12-03 20:24 UTC, tan-90 commented on src/components/botd/HeroSection/HeroSection.tsx
> +          </p>
Does this work for you in Safari? For me it scrolls past the title and cuts a big part of the details section.

2021-12-03 20:24 UTC, tan-90 commented on src/components/common/CodeWindowWithSelector/index.tsx
> +  singleCode?: string
To avoid having a props that shouldn't exist together we could just change this component to receive an array of objects containing a tab name and code. That way if the array only has one element we show the simple code window, if it has more we show tabs.

2021-12-03 20:42 UTC, natapg commented on src/components/common/CodeWindowWithSelector/index.tsx
> +  singleCode?: string
good idea!

2021-12-06 13:37 UTC, natapg commented on src/components/botd/HeroSection/HeroSection.tsx
> +          </p>
yeah,for me too, I have to take a look, but also I'm waiting to have more sections to see how it behaves since in my case it doesn't scroll more because it reaches the end of the page

2021-12-06 13:37 UTC, natapg commented on src/components/common/CodeWindowWithSelector/index.tsx
> +  singleCode?: string
fixed @tan-90

2021-12-06 18:55 UTC, natapg commented on src/components/botd/HeroSection/HeroSection.tsx
> +          </p>
fixed @tan-90 , please check again! the header bar was hiding the element to be scrolled

2021-12-08 17:54 UTC, tan-90 commented on src/components/botd/HeroSection/HeroSection.tsx
> +          </p>
Works perfectly now 🎉

2021-12-08 17:59 UTC, tan-90 approved these changes

2021-12-08 18:01 UTC, merged