Feature/widget card grid
fingerprintjs/fingerprintjs.com pull request #42
Opened 2020-11-25 18:06 UTC by tan-90

2020-11-25 18:16 UTC, tan-90 commented on content/pages/account-sharing-test-page.md
> -    - boop
This was removed on accident

2020-11-26 10:02 UTC, Lisenish requested changes

2020-11-26 10:08 UTC, Lisenish commented
@tan-90 Could you please recreate whole component on the test page? We should have not only Cards Grid but this title and subtitle also, we discussed that we need to create this more complex component from simpler ones. And on the test page use the same copy and icons to see how it'll look like with real usage data.
![image](https://user-images.githubusercontent.com/578625/100337254-34d19280-2fe8-11eb-9d77-92943202a4df.png)

2020-11-27 20:22 UTC, tan-90 commented on src/components/widgets/CardGrid/CardGrid.module.scss
> +  flex: 1 0 auto;
This is to ensure the height stays the same, so I think so. Open to discuss if that's wrong though.

2020-11-27 20:23 UTC, tan-90 commented on src/templates/account-sharing-page.tsx
> +              fluid(maxWidth: 2048, quality: 100) {
That was my bad. I copied the image query from another page and forgot to adjust.

2020-11-27 20:25 UTC, tan-90 commented on src/templates/account-sharing-page.tsx
> +type QueryCard = NonNullable<NonNullable<GatsbyTypes.AccountSharingPageQuery['markdownRemark']>['frontmatter']>['cards']
From `gatsby-types.d.ts`: `readonly cards: Maybe<ReadonlyArray<Maybe<MarkdownRemarkFrontmatterCards>>>;`.

It returns an array, but the actual query type is an array already, correct?

2020-11-30 12:52 UTC, Lisenish commented on src/templates/account-sharing-page.tsx
> +type QueryCard = NonNullable<NonNullable<GatsbyTypes.AccountSharingPageQuery['markdownRemark']>['frontmatter']>['cards']
1. I meant currently this type called like it should represent a singular object but it actually represents an array.
Since it's stub page anyway we can leave it as is, but currently, it also shows types error here, does `yarn lint` work for you? Pls fix it, since it's temporary code anyway you can just type cast it if there is a need
And no `frontmatter` type is not an array, it's metadata of md file, one md file has only one frontmatter meta-data.

2. Can you add https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.md this rule as a warning to eslint and fix it below? You will need also add this override to eslintrc.js
 ```
   {
      files: ['*.ts', '*.tsx'],
      parserOptions: {
        project: './tsconfig.json',
      },
    },
```

2020-12-01 10:32 UTC, Lisenish requested changes

2020-12-01 10:32 UTC, Lisenish commented on src/components/widgets/CardSection/CardSection.module.scss
> +  background-image: url('./CardSectionBackground.png');
Let's use a common naming convention for assets that are not styles, it's usually kebab-case (as we have in other places)

2020-12-01 10:32 UTC, Lisenish commented on src/components/widgets/SubHeader/index.tsx
> +      {subtitle && <h3 className={styles.subtitle}>{subtitle}</h3>}
I thought it should be different components for easier composition, or maybe even one component but with different variants for `variant`/`size` prorerty (e.g. https://material-ui.com/ru/components/typography/, https://chakra-ui.com/docs/typography/heading)

2020-12-01 10:32 UTC, Lisenish commented on src/components/widgets/SubHeader/SubHeader.module.scss
> +    text-align: center;
I think alignment probably should be either customizable or set up on container level styles or this will be less reusable

2020-12-01 10:32 UTC, Lisenish commented on src/components/widgets/SubHeader/index.tsx
> +      {subtitle && <h3 className={styles.subtitle}>{subtitle}</h3>}
Also, you need to replace similar text in other components to use this component ( I think we discussed in Slack that Hero component uses something similar). 
So it will be easier for you to understand how you should implement it so it's reusable when you already have different usage places for it

2020-12-01 10:42 UTC, Lisenish commented
@tan-90 Final fixes and let's merge. Or for simplicity, we can even merge it as is and you can fix final comment in different WIP branch

2020-12-01 12:14 UTC, tan-90 commented on src/components/widgets/SubHeader/index.tsx
> +      {subtitle && <h3 className={styles.subtitle}>{subtitle}</h3>}
Didn't change the header on Hero since the font sizes were different. I'll look through everything on Figma and on our components to see what should be customizable.

2020-12-01 15:33 UTC, Lisenish commented on src/templates/account-sharing-page.tsx
> +    return <></>
You can return null for such cases

2020-12-01 15:34 UTC, merged

2020-12-01 16:23 UTC, tan-90 commented on src/templates/account-sharing-page.tsx
> +    return <></>
I remember it didn't build at some point because of this, so I changed it. Will check and remove if unecessary.

2020-12-02 18:02 UTC, tan-90 commented on src/templates/account-sharing-page.tsx
> +    return <></>
Breaks my build: https://reactjs.org/docs/error-decoder.html/?invariant=152&args[]=CmsStaticPage