Added contact sales form.
fingerprintjs/fingerprintjs.com pull request #43
Opened 2020-11-25 19:12 UTC by tan-90

2020-11-25 20:55 UTC, Lisenish requested changes
LGTM but we need to wait when API is fixed before the merge

2020-11-26 17:22 UTC, Lisenish commented on src/hooks/useForm.ts
> +import FormContext, { Forms, UPDATE_ERROR_MESSAGE, UPDATE_FORM_STATE } from '../context/FormContext'
I think we don't need these separate context file, it's all could be here. But let's do it later

2020-11-26 17:23 UTC, Lisenish commented on src/context/FormContext.tsx
> +  Signup = 'Signup',
I think it would be ok to have regular enum without string values

2020-11-26 17:25 UTC, Lisenish commented on src/context/FormContext.tsx
> +export const UPDATE_FORM_STATE = 'UPDATE_FORM_STATE'
Maybe that's also should be an enum?

2020-11-26 17:28 UTC, Lisenish commented on src/context/FormContext.tsx
> +  Object.keys(Forms).forEach((form) => {
Probably it's better to treat an empty value as a Default state

2020-11-26 17:29 UTC, Lisenish commented on src/hooks/useForm.ts
> +  const updateFormState = (formState: FormState) => {
I think in custom hook, it's better to return memoized functions (use `useCallback`)

2020-11-26 17:37 UTC, merged

2020-11-27 12:26 UTC, tan-90 commented on src/context/FormContext.tsx
> +export const UPDATE_FORM_STATE = 'UPDATE_FORM_STATE'
Changing this to an enum makes TS complain about the type of payload for some reason. I changed it, but we should probably discuss this on a call since it requires some extra changes.

2020-11-27 12:52 UTC, tan-90 commented on src/context/FormContext.tsx
> +  Object.keys(Forms).forEach((form) => {
You mean removing the `Default` entry on the enum and replace it with an empty value?