Added static CMS page.
fingerprintjs/fingerprintjs.com pull request #47
Opened 2020-12-02 18:19 UTC by tan-90

Also addressed change requests from previous PRs.

2020-12-02 18:21 UTC, tan-90 commented on src/components/widgets/SubHeader/index.tsx
> +type SubHeaderTextSize = 'small' | 'normal' | 'medium' | 'large'
Maybe these should be on a common file? We should probably discuss if we're gonna end up using this in other places.

2020-12-04 15:29 UTC, Lisenish requested changes

2020-12-04 15:29 UTC, Lisenish commented on src/components/widgets/InlineCta/InlineCta.module.scss
>      background-image: url('../../../img/bg-full.png');
After we merge tech branch we need to replace it to the new approach (please leave TODO)

2020-12-04 15:29 UTC, Lisenish commented on src/components/widgets/Hero/index.tsx
> +  className?: string | string[]
Ok, just let's fix it everywhere

2020-12-04 15:29 UTC, Lisenish commented on src/components/widgets/SubHeader/index.tsx
> +type SubHeaderTextSize = 'small' | 'normal' | 'medium' | 'large'
While we don't use it in other places it's fine to have it here, let's keep local related things close

2020-12-04 15:29 UTC, Lisenish commented on src/helpers/content.ts
> +export const baseUrl = 'https://fingerprintjs.com'
It should be in `constants/` folder

2020-12-04 15:29 UTC, Lisenish commented on src/templates/account-sharing-page.tsx
>  import { ArrayElement } from '../helpers/types'
We need to delete this

2020-12-04 15:29 UTC, Lisenish commented on content/pages/cms-static-page.md
> +---
Need to change the name but we're waiting for Savannah's input for that

2020-12-04 15:29 UTC, Lisenish commented on static/admin/config.yml
> +        label: 'CMS Static Page'
Need to negotiate name with Savannah

2020-12-04 15:29 UTC, Lisenish commented on src/templates/cms-static-page.tsx
> +                  ...GatsbyImageSharpFixed
Let's try to use `GatsbyImageSharpFixed_withWebp `it should have better performance on Google Chrome, but also test in different browsers after that

2020-12-04 15:29 UTC, Lisenish commented on src/templates/cms-static-page.tsx
> +                  ...GatsbyImageSharpFixed
And same for the image below

2020-12-04 15:30 UTC, Lisenish commented
Good job, only minor things, let's fix them on Monday and deploy after we get final content

2020-12-04 15:36 UTC, Lisenish commented
Do you know why it's empty on the preview?
https://deploy-preview-47--fingerprintjscom.netlify.app/pages/cms-static-page/

2020-12-08 15:40 UTC, Lisenish approved these changes
LGTM, going to merge it to feature branch now

2020-12-08 15:43 UTC, merged