Added blog pages with long-form content template
fingerprintjs/fingerprintjs.com pull request #49
Opened 2020-12-07 20:25 UTC by tan-90

2020-12-09 20:51 UTC, Lisenish requested changes

2020-12-09 20:51 UTC, Lisenish commented on content/blog/blog-test-page.md
> +---
Let's delete this one before the merge.

I will set up storybook this or next week so we don't have to create temp pages to check markup (but locally probably we still have to create the to check generation)

2020-12-09 20:51 UTC, Lisenish commented on src/pages/blog/blog.module.scss
> +.header {
Shouldn't we use our typography header component instead?

2020-12-09 20:51 UTC, Lisenish commented on src/pages/blog/blog.module.scss
> +  &:hover {
I love that you added this nice little touch :) (it's probably from a reference template?)

2020-12-09 20:51 UTC, Lisenish commented on src/pages/blog/index.tsx
> +                  title={post.frontmatter?.metadata?.title ?? ''}
Looks a little dirty, you can destruct all fields to variables (need to convert arrow function to multi-line)

2020-12-09 20:51 UTC, Lisenish commented on gatsby-config.js
> +      resolve: 'gatsby-source-filesystem',
Do we really need to register additional folder if we already registered content?
I think it should pick up sub-folders

2020-12-09 20:51 UTC, Lisenish commented on static/admin/config.yml
> +    create: true
Probably should allow deleting also? Not 100% sure, we may ask Savannah

2020-12-09 20:51 UTC, Lisenish commented on src/templates/long-form-content.tsx
> +  <div className={className}>{content}</div>
Maybe use `children` here instead of a specific named prop?

2020-12-09 20:51 UTC, Lisenish commented on src/templates/long-form-content.tsx
> +  contentComponent?: (props) => JSX.Element
Same here: maybe use `children` here instead of a named prop? Also, it's incorrect typing for a component probably you need just `React.ReactNode` (same for body above)

2020-12-09 21:18 UTC, Lisenish commented
@tan-90 Pls sync this branch with develop

2020-12-09 21:55 UTC, borislobanov92 requested changes

2020-12-09 21:55 UTC, borislobanov92 commented on src/pages/blog/blog.module.scss
> +  &:hover {
++

2020-12-09 21:55 UTC, borislobanov92 commented on src/pages/blog/index.tsx
> +          <Section className={styles.grid}>
I think sections should only be on 1 level, breaking the page content into horizontal blocks. I suggest that you move the h1 to the top of Layout content and keep just the upper level section

2020-12-09 21:55 UTC, borislobanov92 commented on src/pages/blog/blog.module.scss
> +  flex-wrap: wrap;
tbh, it's kinda strange seeing a class named 'grid' with display 'flex'. I would consider using `display: grid` since that's basically what it was created for. this is of course an optional fix but have you tested this with multiple posts? is everything working properly on all screen resolutions?

2020-12-09 21:55 UTC, borislobanov92 commented on src/templates/long-form-content.module.scss
> +  .container {
I don't think we should nest these since it doesn't help us in any way and only generates longer class names and makes it harder to debug in the inspector

2020-12-09 21:55 UTC, borislobanov92 commented on src/templates/long-form-content.module.scss
> +        margin-bottom: 6.75rem;
looks too big on mobile

2020-12-10 08:11 UTC, Lisenish commented on src/templates/long-form-content.module.scss
> +  .container {
Agreed, we even discussed that in some previous PR before with @tan-90. 
Obviously, we need 1 level nesting for elements rules but all other nestings seems excessive

It also leads to some bugs with the background-image plugin we use (it's actually their bug but still)

2020-12-10 12:49 UTC, tan-90 commented on static/admin/config.yml
> +    create: true
That was an oversight yeah, I feel like it would be a problem if all created pages were just permanent.

2020-12-10 12:55 UTC, tan-90 commented on gatsby-config.js
> +      resolve: 'gatsby-source-filesystem',
I got confused with the name and thought we needed one for each subfolder. It does pick everything up without this.

2020-12-10 13:05 UTC, tan-90 commented on src/templates/long-form-content.module.scss
> +  .container {
Not nesting unless it's for element rules is a very good guideline, thank you. I'll start following that.

2020-12-10 13:47 UTC, tan-90 commented on src/templates/long-form-content.tsx
> +  <div className={className}>{content}</div>
Here I don't think we can, because this needs to have the same signature as the `HtmlContent` component so we can pick `HtmlContent` for the actual page and `Content` for the preview. `HtmlContent` expects a string so it can use `dangerouslySetInnerHTML`, which wouldn't work with a ReactNode. Maybe there is a way to do it though, open to suggestions.

I did change the type from `JSX.Element` to `ReactNode`.

2020-12-10 14:01 UTC, tan-90 commented on src/templates/long-form-content.tsx
> +  contentComponent?: (props) => JSX.Element
I changed the type of `body` to `string | React.ReactNode`, but I think it's the same as before, `body` can't be just `children: React.ReactNode` because the template doesn't know which `contentComponent` it's gonna use, and the `HtmlContent` requires a string.

As for the `contentComponent` type, I'm using it on lines 59 and 67 to create a component, not just to render a node. TS complains if the return type is not a `JSX.Element`.

I took this from the starter and added the typing. The `contentComponent` props were missing a type, so I fixed that.

2020-12-10 14:02 UTC, tan-90 commented on src/templates/long-form-content.tsx
> +  <div className={className}>{content}</div>
Unless `children` could be `string | React.ReactNode`. But even if that's possible, I don't think it's a good idea.

2020-12-10 14:05 UTC, tan-90 commented on src/pages/blog/index.tsx
> +          <Section className={styles.grid}>
That was my bad yeah, the header is part of the section. Just changed it to be a single section.

2020-12-11 17:17 UTC, tan-90 commented on src/pages/blog/blog.module.scss
> +  &:hover {
Thanks! It's from here https://www.fastly.com/blog. I wanted to get that "lifting off the background" effect.

2020-12-11 17:20 UTC, tan-90 commented on src/pages/blog/blog.module.scss
> +.header {
The mockup on Figma is just slightly smaller than our typography header. But I do agree that it's better to be consistent, I'll change that.

2020-12-14 12:51 UTC, merged