Authors page facelift
fingerprintjs/fingerprintjs.com pull request #500
Opened 2022-01-27 18:22 UTC by natapg

Closes [WEB-328](https://fpjs.myjetbrains.com/youtrack/issue/WEB-328)

[Mockup](https://www.figma.com/file/niHrIRowTbqQhDO7W5CPNf/FPJS-WEB-UI-%2B?node-id=3278%3A46108)

2022-01-28 17:39 UTC, tan-90 requested changes
Pointed out a couple minor things, requesting changes so we can also discuss some of the questions.

2022-01-28 17:39 UTC, tan-90 commented on src/components/AuthorSummary/AuthorSummary.tsx
> +      <h3 className={styles.articlesTitle}>{`${author} Articles`}</h3>
I'd change it to `${author}'s Articles` but probably better to talk to a native speaker about that.

2022-01-28 17:39 UTC, tan-90 commented on src/templates/author-tag.tsx
> +        </Container>
If we're only using the SEO there's no need to have a container.

2022-01-28 17:39 UTC, tan-90 commented on src/templates/author.tsx
>          </Container>
We can remove the container here as well.

2022-01-28 17:39 UTC, tan-90 commented on src/templates/author.tsx
>              .map((post) => ({ ...post }))}
Why do we need `{ ...post }`? Is it because of typing? Could also change this to use a single map.

2022-01-28 17:39 UTC, tan-90 commented on src/components/AuthorSummary/AuthorSummary.tsx
> +  return (
Since it's only used on the author's page, does it need to be clickable? It would only remove the active tags right?

2022-01-28 18:27 UTC, natapg commented on src/components/AuthorSummary/AuthorSummary.tsx
> +  return (
yeah, that's the idea since we don't have breadcrum here, but I can make it clickable only on the tag page I think

2022-01-28 18:48 UTC, natapg commented on src/components/AuthorSummary/AuthorSummary.tsx
> +      <h3 className={styles.articlesTitle}>{`${author} Articles`}</h3>
good point, I've asked Savannah on our internal channel

2022-01-28 18:49 UTC, natapg commented on src/templates/author.tsx
>              .map((post) => ({ ...post }))}
My bad, I think I had a typing problem at first, but with a single map it's fine, I fixed it

2022-01-28 18:56 UTC, natapg commented on src/components/AuthorSummary/AuthorSummary.tsx
> +      <h3 className={styles.articlesTitle}>{`${author} Articles`}</h3>
@tan-90 Savannah's reply -> yes ’s is right!

2022-01-31 19:01 UTC, tan-90 approved these changes

2022-01-31 19:27 UTC, merged