fix: added phone number to contact sales form
fingerprintjs/fingerprintjs.com pull request #518
Opened 2022-02-10 14:46 UTC by natapg

2022-02-11 17:24 UTC, Lisenish requested changes

2022-02-11 17:24 UTC, Lisenish commented on package.json
> +    "react-phone-input-2": "^2.15.0",
Let's pin it, this library is pretty small and can't be trusted so we need to check every update carefully.

2022-02-11 17:24 UTC, Lisenish commented on src/components/ContactSalesForm/index.tsx
> +  const addPhone = () => {
The usual name convention for even handlers to start them with prefix `handle...` + the name of the event.
So here it should be something like `handlePhoneChange`

2022-02-11 17:24 UTC, Lisenish commented on src/components/ContactSalesForm/index.tsx
> +                onChange={() => addPhone()}
Why not just ?

```suggestion
                onChange={addPhone}
```

2022-02-11 17:24 UTC, Lisenish commented on src/components/ContactSalesForm/index.tsx
> +    const inputElement = document.getElementsByName('phoneInput')[0] as HTMLInputElement
You very rarely need to use raw DOM selectors in React. You need to use `useRef` hook for this and pass it to `inputProps.ref`

2022-02-11 17:24 UTC, Lisenish commented on src/components/ContactSalesForm/index.tsx
> +    setPhone(inputElement.value)
Why're are you using `inputElement.value` here? You should get the phone value from the  handler function arguments

2022-02-14 12:30 UTC, natapg commented on src/components/ContactSalesForm/index.tsx
> +    setPhone(inputElement.value)
I asked Maciej about this, if he needs the number to be formatted or not (like +1 125 2131 1231 vs +112521311231)
in case he needs it formatted, this way I can get it with the format, if he doesn't need it I can get it from the handler function arguments

2022-02-14 12:33 UTC, natapg commented on src/components/ContactSalesForm/index.tsx
> +    const inputElement = document.getElementsByName('phoneInput')[0] as HTMLInputElement
yeah I know, the issue is that I don't have direct access to the input element and that's why I decided to do it this way, but I'll see if I can do it with the inputProps parameter

2022-02-14 13:08 UTC, natapg commented on src/components/ContactSalesForm/index.tsx
> +    const inputElement = document.getElementsByName('phoneInput')[0] as HTMLInputElement
It's possible thanks to this fix :) changing it https://github.com/bl00mber/react-phone-input-2/issues/187

2022-02-14 13:48 UTC, Lisenish approved these changes

2022-02-14 13:48 UTC, Lisenish commented on src/components/ContactSalesForm/index.tsx
> +                onChange={(phone) => handlePhoneChange(phone)}
nit: it can be just this, since signature is the sasme:

```suggestion
                onChange={handlePhoneChange}
```

2022-02-16 13:52 UTC, merged