[WIP] Migrate gatsby config files to TS
fingerprintjs/fingerprintjs.com pull request #543
Opened 2022-03-04 01:16 UTC by natapg

2022-03-07 14:59 UTC, tan-90 requested changes

2022-03-07 14:59 UTC, tan-90 commented on gatsby-node.ts
> +const getArrayFieldValues = async (graphql: CreatePagesArgs['graphql'], name: string) => {
Minor: why change to an arrow function? On the dashboard we usually prefer function declarations.

2022-03-07 14:59 UTC, tan-90 commented on gatsby-node.ts
> +  }
Can we change it to this on all places instead of adding if statements?

```suggestion
 pages?.forEach((edge) => createPageFromEdge(edge, createPage))
```

2022-03-07 14:59 UTC, tan-90 commented on gatsby-node.ts
>    )
If we move the `as AuthorNode[]` to here it will already have the correct type and there will be no need to cast before using it.

2022-03-07 14:59 UTC, tan-90 commented on gatsby-node.ts
> +      const authorsNode = authors as unknown as AuthorNode[]
Doing the change in the previous comment we could get rid of this and just use `authors` instead.

2022-03-08 12:50 UTC, natapg commented on gatsby-config.ts
>        },
I think there is no reason, I will change it

2022-03-08 12:58 UTC, natapg commented on gatsby-node.ts
> +const getArrayFieldValues = async (graphql: CreatePagesArgs['graphql'], name: string) => {
I just followed the Gatsby migration guide which uses arrow functions, but I can change it

2022-03-08 14:08 UTC, natapg commented
@tan-90 I've made the changes that you requeted! thanks!

2022-03-09 14:16 UTC, tan-90 approved these changes

2022-03-09 16:15 UTC, merged