Fix url slashes
fingerprintjs/fingerprintjs.com pull request #57
Opened 2020-12-16 21:50 UTC by natapg

I added the URLs to the content.ts file and changed them in the index pages. We need to discuss if this way of saving URLs as constants is ok

2020-12-17 20:41 UTC, Lisenish requested changes

2020-12-17 20:41 UTC, Lisenish commented on src/components/GithubButton/index.tsx
> +  const url = githubApiUrl
No point in this variable now, you can inline it

2020-12-17 20:41 UTC, Lisenish commented on src/constants/content.ts
> +export const demoUrl = '/demo/'
Let's semantically group them in this way 
`export const URL = {
  example: 'https://example.com'
} as const`

Groups can be: DOC_URL (for documentation), PATH (for internal relative links), URL(for external urls), MAILTO (for one mailto link)
In that case we even don't need url postfixes

Also let's rename baseUrl to BASE_URL.

2020-12-17 20:41 UTC, Lisenish commented on src/constants/content.ts
> +export const getStartedUrl = 'https://dev.fingerprintjs.com/docs/introduction'
We discussed that we can change it in this branch

2020-12-17 20:43 UTC, Lisenish commented
@natapg I see that you skipped e-commerce card link. This one is trickier because it's generated, try to figure out how to fix it, but if you're stuck ask @tan-90 for help

2020-12-17 20:45 UTC, tan-90 reviewed
Looks good to me. Just need @Lisenish confirmation about trailing slashes.

2020-12-17 20:45 UTC, tan-90 commented on src/components/GithubButton/index.tsx
>    const { data } = useFetch<GithubReposResponse>(url, options)
Could inline `githubApiUrl` here.

2020-12-17 20:45 UTC, tan-90 commented on src/constants/content.ts
>  export const baseUrl = 'https://fingerprintjs.com'
Shouldn't all of these have a trailing slash? @Lisenish

2020-12-17 20:52 UTC, Lisenish commented on src/constants/content.ts
>  export const baseUrl = 'https://fingerprintjs.com'
Only internal ones, it doesn't matter for external (non-website) urls.

A little context: the reason we need trailing slashes because of this Netlify behaviour:

> Our CDN edge nodes do URL normalization before the redirect rules kick in. This happens to make sure we can guarantee the highest possible cache hit rate and the absolute best performance for your site.

And redirects are bad for SEO, so the only options for us to lead to the correct url from the start.

2020-12-21 16:17 UTC, Lisenish approved these changes

2020-12-21 16:24 UTC, merged