Static page links
fingerprintjs/fingerprintjs.com pull request #58
Opened 2020-12-17 18:41 UTC by tan-90

Adds links to static pages to the footer.
Breaks up the top navbar into left and right nav.

Depends on feature/static-pages

2020-12-18 11:19 UTC, Lisenish requested changes

2020-12-18 11:19 UTC, Lisenish commented on src/components/Header/index.tsx
> +interface DropdownListProps {
Let's move it to separate file it's complex enough component and it has big chunk of the styles

2020-12-18 11:19 UTC, Lisenish commented on src/components/MobileNavbar/index.tsx
> +interface DropdownMenuProps {
Same here

2020-12-18 11:19 UTC, Lisenish commented on src/components/Header/index.tsx
> +import { ReactComponent as ExpandMoreSvg } from '../../img/expand-more.svg'
Do we use it somewhere else? Maybe it should be a local icon?

2020-12-18 11:19 UTC, Lisenish commented on src/constants/content.ts
> +  { title: 'Account Takeover', url: '/account-takeover/', isLocal: true },
`isLocal` probably excessive since it's true by default?

2020-12-18 11:26 UTC, Lisenish commented on src/components/Navbar/index.tsx
> +            Login
Is it intentional change? Maybe we should change it everywhere then? It's Log In in other places

2020-12-18 12:56 UTC, tan-90 commented on src/constants/content.ts
> +  { title: 'Account Takeover', url: '/account-takeover/', isLocal: true },
I added this was to make it compatible with the type the footer is expecting:
```
interface FooterLinkSection {
  title: string
  links: { title: string; url: string; isLocal?: boolean }[]
}
```

The footer considers `false` as the default, so changing that would risk breaking something.

2020-12-18 12:57 UTC, tan-90 commented on src/constants/content.ts
> +  { title: 'Account Takeover', url: '/account-takeover/', isLocal: true },
Or I could just remove it and then map each link to the expected type on the Footer. I'm ok with either solution.

2020-12-18 12:58 UTC, tan-90 commented on src/components/Header/index.tsx
> +import { ReactComponent as ExpandMoreSvg } from '../../img/expand-more.svg'
We use it on the Collapsible as well, but it's local for the collapsible. I'll fix that.

2020-12-18 13:07 UTC, tan-90 commented on src/components/Navbar/index.tsx
> +            Login
It was written Login on the list Savannah provided, but I forgot to check other places. I'll confirm with her just to make sure.

2020-12-21 16:34 UTC, tan-90 commented on src/components/Navbar/index.tsx
> +            Login
Discussed with Savannah, changed all occurrences to "login".

2020-12-22 10:25 UTC, Lisenish approved these changes

2020-12-23 11:40 UTC, merged