Fix: added visits loading state
fingerprintjs/fingerprintjs.com pull request #587
Opened 2022-04-13 23:43 UTC by natapg

Closes [WEB-403](https://fpjs.myjetbrains.com/youtrack/issue/WEB-403)

2022-04-14 12:20 UTC, natapg commented on src/components/FpjsWidget/FpjsWidget.module.scss
> -  &.loaded {
with the loading status it is not necessary to hide the tooltip icon

2022-04-14 17:55 UTC, Lisenish requested changes
@natapg I've left some comments please take a look.
I also noticed that we always render both mobile and desktop versions, could you please remind me, it's because of the SSR? I'm not sure if it's the best decision, we probably need to discuss and potentially create a separate ticket for that

2022-04-14 17:55 UTC, Lisenish commented on src/components/FpjsWidget/index.tsx
> +  const { getData, error, isLoading: fjpsIsLoading } = useVisitorData(getConfig, { immediate: false })
We can rename `error` here to `indeficationError`.  And `hasError` to something like `historyLoadError`
Then we can declare a variable `const hasError = indeficationError || historyLoadError`

In this case we won't need this code below in the effect
```    
if (error) {
      setHasError(true)
      return
    }
```

2022-04-14 17:55 UTC, Lisenish commented on src/components/FpjsWidget/index.tsx
> +  const { getData, error, isLoading: fjpsIsLoading } = useVisitorData(getConfig, { immediate: false })
We can rename `error` here to `indeficationError`.  And `hasError` to something like `historyLoadError`
Then we can declare a variable `const hasError = indeficationError || historyLoadError`

In this case we won't need this code below in the effect
```    
if (error) {
      setHasError(true)
      return
    }
```

2022-04-14 17:55 UTC, Lisenish commented on src/components/FpjsWidget/index.tsx
> +  const { getData, error, isLoading: fjpsIsLoading } = useVisitorData(getConfig, { immediate: false })
typo, should be`**fpjs**IsLoading`

2022-04-14 17:55 UTC, Lisenish commented on src/components/FpjsWidget/index.tsx
> +  const { getData, error, isLoading: fjpsIsLoading } = useVisitorData(getConfig, { immediate: false })
typo, should be`**fpjs**IsLoading`

2022-04-14 17:55 UTC, Lisenish commented on src/components/FpjsWidget/index.tsx
> +function FullLoadingState({ hasError }: LoadingStateProps) {
Why is is called `Full...`? Maybe `DetailsLoadingState`/ `VisitDetailsLoadingState`/`VisitDetailsSkeleton` would be better?

2022-04-14 17:55 UTC, Lisenish commented on src/components/FpjsWidget/index.tsx
> +function FullLoadingState({ hasError }: LoadingStateProps) {
Ok figured it out, I think you incorrectly composed component, we shouldn't manually compose all the possible states, we should rather have two components: one for histroy and the other for details part and they both should have their own loading state. 
It should be something like this:

```html
<div className={styles.container}>
  <VistHistory isLoading={isVisitHistoryLoading} ... />
  <VistDetails isLoading={isVisitDetailsLoading} ... />
</div>
```

So in this way you don't need to manually crate combinations fro the state when you have only visits loading, or both, or only details

2022-04-14 17:55 UTC, Lisenish commented on src/components/FpjsWidget/index.tsx
> +function FullLoadingState({ hasError }: LoadingStateProps) {
In general it should look something like this:

```jsx 
if (hasError) {
 return <FpjsWidgetLoaded hasError />
}

if (isVisitHistoryLoading || isVisitDetailsLoading) {
  return <LoadingState isVisitDetailsLoading={isVisitDetailsLoading} isVisitDetailsLoading={isVisitDetailsLoading}  />

return <FpjsWidgetLoaded ... />
  
}
```

2022-04-14 20:21 UTC, natapg commented
thanks @Lisenish , I think I got your idea, please check :)

2022-04-18 20:08 UTC, Lisenish approved these changes
@natapg Good job, much cleaner 👍 Only one nitpick

2022-04-18 20:08 UTC, Lisenish commented on src/components/FpjsWidget/index.tsx
> +    error: indeficationError,
nit: `indefication` is not a word

2022-04-18 20:39 UTC, merged