WIP Implement greenhouse internal pages
fingerprintjs/fingerprintjs.com pull request #618
Opened 2022-05-19 21:53 UTC by natapg

2022-05-25 20:16 UTC, tan-90 requested changes

2022-05-25 20:16 UTC, tan-90 commented on src/pages/careers/jobs/index.tsx
> +          })
Minor: no need for a function body

2022-05-25 20:16 UTC, tan-90 commented on src/pages/careers/jobs/index.tsx
> +      .catch(() => onError())
Minor: I'd change this to be an async function as well.

2022-05-25 20:16 UTC, tan-90 commented on src/pages/careers/jobs/index.tsx
> +                <Select
Minor: I think the default select highlight color doesn't match the style very well.

2022-05-26 13:02 UTC, natapg commented on src/pages/careers/jobs/apply/index.tsx
> +import { scrollToElementById } from '../../../../helpers/scrollToElementBytID'
yeah, you are right! I'll create a ticket

2022-05-27 18:24 UTC, tan-90 approved these changes

2022-05-31 16:25 UTC, merged