Generate sitemap.xlm and robots.txt
fingerprintjs/fingerprintjs.com pull request #63
Opened 2020-12-22 16:53 UTC by natapg

2020-12-22 20:08 UTC, Lisenish commented
Pls delete `package-lock.json` file, we use yarn

2020-12-22 20:08 UTC, Lisenish requested changes

2020-12-22 20:08 UTC, Lisenish commented on gatsby-config.js
> +    siteUrl: 'https://fingerprintjs.com',
You probably can't use TS file here, I get it, but you can still move this string to the constant variable in this file

2020-12-22 20:17 UTC, natapg commented on gatsby-config.js
> +    siteUrl: 'https://fingerprintjs.com',
you're right, I'm going to make the change

2020-12-22 20:18 UTC, natapg commented on gatsby-config.js
> +    siteUrl: 'https://fingerprintjs.com',
you're right, I'm going to move it to a constant variable

2020-12-23 11:33 UTC, Lisenish commented on gatsby-config.js
> +    url: baseUrl,
@tan-90 AFAIK It's common to have it called stiteUrl in metadata and some plugins rely on that convention, so we need to refactor url usages to use siteUrl intead (in some separate task)

2020-12-23 11:33 UTC, Lisenish approved these changes

2020-12-23 11:37 UTC, merged