Added featured posts.
fingerprintjs/fingerprintjs.com pull request #64
Opened 2020-12-22 20:12 UTC by tan-90

Added `FEATURED` switch to CMS.
Added featured posts section to blog landing page.
Added landing page for featured posts.

2020-12-23 23:14 UTC, Lisenish commented
@tan-90 Please update sync develop branch

2020-12-24 20:09 UTC, Lisenish requested changes

2020-12-24 20:09 UTC, Lisenish commented on src/templates/blog.module.scss
> -.grid {
Nice :)

2020-12-24 20:09 UTC, Lisenish commented on src/templates/blog.tsx
> +  fragment PostData on MarkdownRemarkConnection {
👍 

I believe you can actually even separate fragment to another exported const with arbitrary name just to have only page query in pageQuery const

2020-12-24 20:09 UTC, Lisenish commented on src/templates/blog-featured.tsx
> +const dateFormatter = new Intl.DateTimeFormat('en-US', { month: 'long', day: 'numeric', year: 'numeric' })
Just left a comment in another review that we probably should have all formatter in one common place

2020-12-24 20:18 UTC, Lisenish commented
@tan-90 I think we should delete our test post and feature some existing one, so we don't ship these test page on production :)

2020-12-29 09:40 UTC, Lisenish approved these changes

2020-12-29 10:01 UTC, Lisenish commented
@tan-90 For some reason there are old link in blog cards? Something merged incorrectly or we need another sync with develop?

2020-12-29 12:11 UTC, tan-90 commented
> @tan-90 For some reason there are old link in blog cards? Something merged incorrectly or we need another sync with develop?

They're like that on develop as well. Maybe it never changed? I think me and Natanael were working in parallel at the time. I'll fix it now.

2020-12-29 12:55 UTC, Lisenish commented
@tan-90 It's good that you fixed that ones, but I actually meant blog posts cards not use cases, looks like they use old filename urls instead of metaurl

2020-12-29 21:09 UTC, merged