added position:fixed to body css when mobile menu is open
fingerprintjs/fingerprintjs.com pull request #71
Opened 2020-12-28 13:27 UTC by natapg

Added **position:fixed** to css to disable scrolling the document body when the mobile menu is open
Closes WEB-65

2020-12-28 14:06 UTC, natapg commented
In Android the menu is no longer scrollable with this solution, I will look for another @Lisenish

2020-12-29 00:06 UTC, natapg commented
I found out that for some reason the style wasn't applied when opening the menu so I had to add "!Important" to it to override the default style

![image](https://user-images.githubusercontent.com/47128448/103249861-f36a3500-494f-11eb-98ce-43bbf0f5a5ec.png)

![image](https://user-images.githubusercontent.com/47128448/103249826-d6cdfd00-494f-11eb-8379-9d2e9537d0b6.png)

2020-12-29 09:57 UTC, Lisenish requested changes

2020-12-29 09:57 UTC, Lisenish commented on src/styles/global-styles.scss
> +    overflow: hidden !important;
Adding important is almost always is a bad idea and dirty fix, please figure out how to fix it properly, you probably need increase specificity of the selector (https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)

2020-12-29 15:05 UTC, natapg commented on src/styles/global-styles.scss
> +    overflow: hidden !important;
Thanks. I was using !Important to override the inline style

2020-12-30 10:41 UTC, Lisenish requested changes

2020-12-30 10:41 UTC, Lisenish commented on src/styles/global-styles.scss
> +    overflow: hidden ;
Trailing whitespace

2020-12-30 10:41 UTC, Lisenish commented on src/components/Header/index.tsx
> +    if (isBrowser && isMobileMenuOpen) {
Discussed in DM to change Menu instead so it resotres original `body.overflow` style.

P.s. @tan-90 remember we discussed such potential bug in review? :)

2020-12-31 08:25 UTC, Lisenish requested changes

2020-12-31 08:25 UTC, Lisenish commented on src/components/Header/index.tsx
> +    isBrowser && isMobileMenuOpen
Minor code style issue: it's better to use ternary operator only for the places where you need expression, e.g. assigning new variable `const x = condition ? 1 : 0`, because the result of this expression is actully what you need.
For the places like here, where you actually use statements (imperative modifying code, and you don't doesn't return any value) it's better to stick to regular if/else (even if they consist from one line)

2020-12-31 15:05 UTC, Lisenish approved these changes

2020-12-31 15:05 UTC, merged