Added related articles.
fingerprintjs/fingerprintjs.com pull request #75
Opened 2020-12-31 12:58 UTC by tan-90

Closes WEB-60

2021-01-06 22:01 UTC, Lisenish requested changes
Only minor things, mostly questions

2021-01-06 22:01 UTC, Lisenish commented on src/components/RelatedArticles/RelatedArticles.tsx
> +        return <PostGrid posts={getRelatedArticles(article, allArticles, count)} name='Related Articles' narrow />
So if we don't have any related articles there will be only title? Maybe we shouldn't show related articles block at all then?

2021-01-07 17:21 UTC, tan-90 commented on src/components/RelatedArticles/RelatedArticles.tsx
> +    <StaticQuery<GatsbyTypes.RelatedArticlesQuery>
I tried the hook, but it breaks the entire preview when it fails to fetch, the render props version breaks more nicely. The fetch should never fail on production, but I just thought it was better to keep the safer version. If needed, it's an easy change though.

2021-01-07 17:23 UTC, tan-90 commented on src/components/RelatedArticles/RelatedArticles.tsx
> +        return <PostGrid posts={getRelatedArticles(article, allArticles, count)} name='Related Articles' narrow />
Oh, that was an oversight, my bad. Fixing now.

2021-01-07 17:45 UTC, tan-90 commented on src/components/PostGrid/PostGrid.tsx
> +  narrow?: boolean
Went with "perRow" here, default being four and narrow being three.

2021-01-07 17:58 UTC, tan-90 commented on src/components/RelatedArticles/RelatedArticles.tsx
> +        node {
Good point, I forgot that they worked across files.

2021-01-12 13:46 UTC, Lisenish commented on src/components/RelatedArticles/RelatedArticles.tsx
> +    <StaticQuery<GatsbyTypes.RelatedArticlesQuery>
Ok no, no need to change it if it's useful I just thought maybe it's some overlook.

2021-01-12 13:47 UTC, Lisenish approved these changes

2021-01-12 13:48 UTC, merged