fix: layout for visitor info icon
fingerprintjs/fingerprintjs.com pull request #84
Opened 2021-01-07 07:37 UTC by spalt08

2021-01-07 08:36 UTC, Lisenish requested changes

2021-01-07 08:36 UTC, Lisenish commented on src/components/FpjsWidget/FpjsWidget.module.scss
>            &:not(.browser) {
We also have Mobile widget, let's do the same there, it reproduces only on very small screens there but just in case...

2021-01-07 08:36 UTC, Lisenish commented on src/components/FpjsWidget/FpjsWidget.module.scss
> +          margin-left: 0 !important;
I see that there is !important above for the height aldready but it's probably was just migrated from legacy styles, can't we increase specificity to avoid it?

2021-01-07 10:47 UTC, Lisenish commented
Still broken if content on the left column is wide enough. 
The thing with this bug it's flaky because it depends on the dates in the left column, and that's why it's not reproduced  for everyone anytime. 
Probably should set mac width and overflow for the left column or forbid grow at all

![image](https://user-images.githubusercontent.com/578625/103883607-804e8480-50ee-11eb-9f4d-ea0d63fbdb7e.png)

2021-01-12 10:39 UTC, spalt08 commented on src/components/FpjsWidget/FpjsWidget.module.scss
>            &:not(.browser) {
fixed

2021-01-12 10:42 UTC, spalt08 commented on src/components/FpjsWidget/FpjsWidget.module.scss
> +          margin-left: 0 !important;
styles are so complicated, so I am not able to figure out how to remove !important here, sorry
I can spend more time on it later in the end of January

2021-01-12 13:26 UTC, Lisenish commented on src/components/FpjsWidget/FpjsWidget.module.scss
> +          margin-left: 0 !important;
No, it's too extreme for such minor thing to get back to it in Jan, ok it's fine we have a lot of them from legacy one more wouldn't kill anybody, thanks :)

2021-01-12 13:44 UTC, Lisenish approved these changes

2021-01-12 13:44 UTC, merged