Created case study page layout.
fingerprintjs/fingerprintjs.com pull request #94
Opened 2021-01-14 14:39 UTC by tan-90

2021-01-18 11:52 UTC, Lisenish requested changes

2021-01-18 11:52 UTC, Lisenish commented on src/components/TitledParagraph/TitledParagraph.module.scss
> +  font-size: 2.75rem;
I see that we often put font styles in-place. Looks like if we decide to change uniform sizes of our headers it would be a lot of work.

We need some good approach for typography, I will create task for this

2021-01-18 11:52 UTC, Lisenish commented on src/components/TitledParagraph/TitledParagraph.module.scss
> +  & + .root {
Root inside root? Looks strange

2021-01-18 11:52 UTC, Lisenish commented on src/components/CustomerOverview/CustomerOverview.tsx
> +  bullets: Array<{ value: string; description: string }>
Probably it's better to extract to own type, when you also can just use `Bullet[]` type

2021-01-18 11:52 UTC, Lisenish commented on src/pages/case-study/index.tsx
> +  let siteMetadata = useSiteMetadata()
I know it's not directly related to this MR but can we refactor this a bit, so it should work like this:

`const siteMetadata = useSiteMetadata({pageOverridesHere})`

2021-01-18 11:52 UTC, Lisenish commented on src/pages/case-study/index.tsx
> +    <footer>
It's great that we use semantic html, but we should follow its rules then. 

There can only be one header and footer element within one section, now we have two adjacent footer tags.
You should either change this to section or wrap everything in content section with it's own header and footer and everything else in between

![image](https://user-images.githubusercontent.com/578625/104908123-0c866480-5997-11eb-996a-a5c320c17c6e.png)

2021-01-18 11:52 UTC, Lisenish commented on src/pages/case-study/case-study.module.scss
> +.downloadPdf {
Shouldn't it be another button variant? Or you don't expect such button on other pages so we treat it like one-off in-place customisation?

2021-01-18 11:52 UTC, Lisenish commented on src/pages/case-study/index.tsx
> +              FingerPrintJS helped us solve our account sharing problem in a manner that was both datadriven and, most
Please check `datadriven` spelling with Savannah, I feel like it should be `data-driven`

2021-01-18 11:52 UTC, Lisenish commented on src/pages/case-study/index.tsx
> +        secondaryHref='mailto:sales@fingerprintjs.com'
I think we should replace `mailto` with contact sales popup, but pls discuss with Savannah first

2021-01-18 11:52 UTC, Lisenish commented on src/pages/case-study/case-study.module.scss
> +  // This will be generated from markdown when we use the CMS so we have to use element selectors.
Shouldn't this styles be used from Content and Blockquote components?

2021-01-18 11:52 UTC, Lisenish commented on src/components/widgets/SubHeader/index.tsx
> +      {labeled ? (
Very hard to read and also looks like there's a lot of duplication.

Remember that you can assign elements to variables and use them later
Labeled prop is not clear for me, as I understand it influences subtitle place? Maybe we should call it subtitlePosition = 'top' | 'bottom'? 
Another variant we can have two props `subtitle` and `label` and choose position based on it, but we should rename size and weight props too then

2021-01-18 12:13 UTC, tan-90 commented on src/components/BlockQuote/BlockQuote.module.scss
> +  position: relative;
The quotes `:after` element doesn't show up otherwise.

2021-01-18 12:32 UTC, tan-90 commented on src/components/Content/Content.tsx
> +export function HtmlContent({ content, className }: { content: string; className?: string }) {
The `HtmlContent` and `Content` components need to have the same signature so we can use them interchangeably on the CMS to handle both preview and actual rendering. So changing the prop would require the safe component to have the same name. I changed the component name to `DangerouslyRenderHtmlContent` instead.

2021-01-18 12:34 UTC, tan-90 commented on src/components/TitledParagraph/TitledParagraph.module.scss
> +  & + .root {
`& + .root` makes the top margin a bit bigger when there are to `TitledParagraph` (roots) right next to each other.

2021-01-18 12:49 UTC, tan-90 commented on src/components/CustomerOverview/CustomerOverview.module.scss
> +  display: grid;
The reason for using grid was that we need the gaps to be aligned. With flex that would require 2 extra classes for the number and the label to set flex-grow, which felt a lot less clean.
![image](https://user-images.githubusercontent.com/10968161/104917446-2d888e80-5972-11eb-8116-5de4a97105b9.png)

2021-01-18 17:34 UTC, tan-90 commented on src/pages/case-study/index.tsx
> +  let siteMetadata = useSiteMetadata()
The main problem with that is the `siteUrl`. When we use the hooks and override the `siteUrl`, we need to do `${metadata.siteUrl}${pathname}`, otherwise we can't use relative paths.

It's possible to assume the passed override is always relative and do `${metadata.siteUrl}${pathname}` inside the hook, but that feels misleading as override implies the value would be replaced.

Open to discussion on how to handle it.

2021-01-18 18:09 UTC, tan-90 commented on src/components/Content/Content.module.scss
> +  blockquote {
`@use` would be better, but since `@use` statements have to be before every other statement, we wouldn't be able to add them to a module. Having to use the CSS loader config to prepend `@use` directives for the styling of a common component sounds overkill and out of place, so I went with `@import`.

2021-01-18 18:11 UTC, tan-90 commented on src/pages/case-study/case-study.module.scss
> +  // This will be generated from markdown when we use the CMS so we have to use element selectors.
The content component allows for a class to be given as an override for the styles of generated content. I used that to make some changes to the default styling as it looked wrong when used to recreate the case-study pdf.

2021-01-28 21:22 UTC, Lisenish approved these changes
Approved in advance, please merge after the fixes

2021-01-29 12:22 UTC, tan-90 commented on src/pages/case-studies/edtech/business-and-finance.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Optimized all of them for consistency.

2021-01-29 12:27 UTC, tan-90 commented on src/templates/case-studies.tsx
> +// import { PostProps } from '../components/Post/Post'
Yeah, I was writing at least the base for the CMS code, then commenting out some parts and replacing them with hardcoded values. I was thinking about how to handle this before the merge, probably gonna delete all the comments and them get them back from history when we integrate the CMS.

2021-01-29 12:37 UTC, tan-90 commented on src/components/FeatureList/FeatureList.tsx
> +    <span className={styles.checkbox}>
Correct, not sure why I did that. Changed it to be just the styled SVG.

2021-02-01 11:02 UTC, Lisenish commented
@tan-90 The link in case studies landing pages doesn't work

2021-02-01 11:03 UTC, Lisenish requested changes
@tan-90 The link in case studies landing pages doesn't work

2021-02-01 15:41 UTC, Lisenish commented on src/templates/long-form-content.tsx
> +    <AppProviders>
Maybe we should extract these to something like `CMSPreviewProviders`?
It's minor duplication now, so up to you, I will approve it

2021-02-01 15:41 UTC, Lisenish approved these changes

2021-02-01 16:27 UTC, merged