Removed logo swipper and added more logos.
fingerprintjs/fingerprintjs.com pull request #99
Opened 2021-01-19 19:40 UTC by tan-90

Changed the client section so it always shows all logos.

2021-01-19 20:00 UTC, Lisenish commented
Probably title should't break now when we have wider content, looks strange
![image](https://user-images.githubusercontent.com/578625/105086424-09c86400-5aaa-11eb-8ca6-81b527a3fb66.png)

2021-01-19 20:02 UTC, Lisenish requested changes

2021-01-19 20:02 UTC, Lisenish commented on src/components/ClientsSection/index.tsx
>  SwiperCore.use([Pagination])
Why is it still here? I think we removed slider, right? Check also if we even need this lib now at all (probably we do for mobile demo swiper, but not sure)

2021-01-19 20:15 UTC, tan-90 commented on src/components/ClientsSection/index.tsx
>  SwiperCore.use([Pagination])
We still need it for the mobile demo, but yeah this was my bad. Removing the imports.

2021-01-20 12:57 UTC, Lisenish approved these changes

2021-01-20 12:57 UTC, merged